name: ManicAI
options:
  bundleIdPrefix: org.uprootiny
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
packages: {}
targets:
  ManicAI:
    type: application
    platform: macOS
    sources:
      - path: ManicAI
    info:
      path: ManicAI/Info.plist
      properties:
        CFBundleDisplayName: ManicAI
        CFBundleIdentifier: org.uprootiny.manicai
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSMinimumSystemVersion: "13.0"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    settings:
      base:
        PRODUCT_NAME: ManicAI
        PRODUCT_BUNDLE_IDENTIFIER: org.uprootiny.manicai
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: ManicAI/Info.plist
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    scheme:
      testTargets:
        - ManicAITests

  ManicAILegacy:
    type: application
    platform: macOS
    sources:
      - path: ManicAILegacy
    info:
      path: ManicAILegacy/Info.plist
      properties:
        CFBundleDisplayName: ManicAI Legacy
        CFBundleIdentifier: org.uprootiny.manicai.legacy
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSMinimumSystemVersion: "10.11"
        NSHighResolutionCapable: true
    settings:
      base:
        PRODUCT_NAME: ManicAILegacy
        PRODUCT_BUNDLE_IDENTIFIER: org.uprootiny.manicai.legacy
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: ManicAILegacy/Info.plist
        MACOSX_DEPLOYMENT_TARGET: "10.11"
        SWIFT_VERSION: "5.9"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  ManicAITests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ManicAITests
    settings:
      base:
        PRODUCT_NAME: ManicAITests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: ManicAI
